[package]
name = "kube-node-label-global-ips"
version = "0.1.0"
edition = "2024"

[dependencies]
miette = "7.6.0"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json"] }
